bump version number
clippercard/clippercard-python pull request #1
Opened 2017-09-03 20:23 UTC by markmark1

fixes bug please make 

In addition to your existing fixes, please bump the lib version references to 0.3.3 in the pull request. That way, I can publish it to pypi for you.

That is, change these references to 0.3.3

$ git grep 0.3.2
CHANGES.txt:v0.3.2, 2014-05-01 Update configparser lib version to 3.5.0b2
clippercard/__init__.py:__version__ = '0.3.2'
setup.py:    version='0.3.2',

Additionally, if you accept, I'm happy to grant you co-ownership of the PyPi project at https://pypi.python.org/pypi/clippercard so you can be empowered to publish revisions in the future.

2017-09-03 20:23 UTC, markmark1 commented
pls make new release on pypi

2017-09-05 07:21 UTC, goldengate88 requested changes
one more changelog request, and I'd be happy to merge and publish 0.3.3

2017-09-05 07:21 UTC, goldengate88 commented on CHANGES.txt
> -v0.3.2, 2014-05-01 Update configparser lib version to 3.5.0b2
one more small fix please, you actually erased the changelog for the previous version 0.3.2, what I meant here was to:

1. add a new line on top describing the changes in your fix, something like: `v0.3.3, 2017-09-05 fixed html parsing, restored functionality`
2. preserve the previous line on 0.3.2

2017-09-05 07:22 UTC, goldengate88 commented
Thank you @markmark1 for fixing this long standing and unfortunately ignored bug. We appreciate your contribution to this project.

2017-09-05 09:43 UTC, markmark1 commented
Ying s pls change it and merge and submit

________________________________
From: Ying Zheng <notifications@github.com>
Sent: Tuesday, September 5, 2017 12:21:09 AM
To: clippercard/clippercard-python
Cc: markmark1; Author
Subject: Re: [clippercard/clippercard-python] bump version number (#1)


@goldengate88 requested changes on this pull request.

one more changelog request, and I'd be happy to merge and publish 0.3.3

________________________________

In CHANGES.txt<https://github.com/clippercard/clippercard-python/pull/1#discussion_r136910685>:

> @@ -1,4 +1,4 @@
-v0.3.2, 2014-05-01 Update configparser lib version to 3.5.0b2


one more small fix please, you actually erased the changelog for the previous version 0.3.2, what I meant here was to:

  1.  add a new line on top describing the changes in your fix, something like: v0.3.3, 2017-09-05 fixed html parsing, restored functionality
  2.  preserve the previous line on 0.3.2

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/clippercard/clippercard-python/pull/1#pullrequestreview-60512734>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AGHomzCJBto2REMvGiSS_TUExJDG0P-Yks5sfPZlgaJpZM4PLStX>.

2017-09-05 16:54 UTC, goldengate88 commented
@markmark1 - I cannot change your source branch to update this PR because the source repo is yours. Ideally, all encompassing commits for a particular change should come in a consolidated PR instead of multiple people piecemealing it together. Generally it's up to the PR author (you) to submit follow-up until all review requests are fulfilled.

This time I will make an exception and merge this PR as is.

Thanks again and you're welcome to submit future changes.

2017-09-05 16:54 UTC, goldengate88 approved these changes

2017-09-05 16:54 UTC, merged

2017-09-05 17:16 UTC, goldengate88 commented
1. changelogs and docs updated in #2 
1. https://pypi.python.org/pypi/clippercard/0.3.3 should be available soon